### ISSUE TITLE
Can not compile with Kernel 5.19

### ISSUE THREAD

**Issue by cbkadal** [jserv/simplefs#21]
It works until kernel 5.18. But I can not compile this with kernel 5.19. Did I miss any CONFIGS?
```
file.c:86:12: error: implicit declaration of function ‘mpage_readpage’; did you mean ‘mpage_writepage’? [-Werror=implicit-function-declaration]
   86 |     return mpage_readpage(page, simplefs_file_get_block);
      |            ^~~~~~~~~~~~~~
      |            mpage_writepage
```
